import type { Metadata } from "next";
import { fontSans } from "@/fonts";

import { PageLayout } from "@/components/layout/page/page";

import "@/styles/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${fontSans.variable} antialiased`}>
        <PageLayout>{children}</PageLayout>
      </body>
    </html>
  );
}
